WIP: unit test refactoring for master
AssetMantle/modules pull request #121
Opened 2022-11-07 11:06 UTC by 0xankit

## Description

Closes: #XXXX

---

### Author Checklist

*All items are required. Please add a note to the item if the item is not applicable and please add links to any
relevant follow-up issues.*

I have...

- [ ] included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json)
  in the PR title
- [ ] added `!` to the type prefix if API or client breaking change
- [ ] targeted the correct branch (
  see [PR Targeting](https://github.com/AssetMantle/modules/blob/master/CONTRIBUTING.md#pr-targeting))
- [ ] provided a link to the relevant issue or specification
- [ ] followed the guidelines
  for [building modules](https://github.com/AssetMantle/modules/blob/master/docs/building-modules)
- [ ] included the necessary unit and
  integration [tests](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#testing)
- [ ] added a changelog entry to `CHANGELOG.md`
- [ ] included comments for [documenting Go code](https://blog.golang.org/godoc)
- [ ] updated the relevant documentation or specification
- [ ] reviewed "Files changed" and left comments if necessary
- [ ] confirmed all CI checks have passed

### Reviewers Checklist

*All items are required. Please add a note if the item is not applicable and please add your handle next to the items
reviewed if you only reviewed selected items.*

I have...

- [ ] confirmed the
  correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] confirmed `!` in the type prefix if API or client breaking change
- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed state machine logic
- [ ] reviewed API design and naming
- [ ] reviewed documentation is accurate
- [ ] reviewed tests and test coverage
- [ ] manually tested (if applicable)

2022-11-09 09:39 UTC, muku314115 commented on modules/identities/internal/transactions/define/keeper_test.go
> +	base2 "github.com/AssetMantle/modules/schema/lists/base"
Can we change this to baseLists and apply such changes for other imports as well

2022-11-10 06:47 UTC, muku314115 commented on modules/identities/internal/transactions/issue/keeper_test.go
> +	base3 "github.com/AssetMantle/modules/schema/ids/base"
rename please

2022-11-10 06:49 UTC, muku314115 requested changes
imports need to follow proper nomenclature

2022-11-11 06:52 UTC, deepanshutr approved these changes
Reviewed.

2022-11-12 11:05 UTC, muku314115 approved these changes

2022-11-14 06:41 UTC, merged