tests: assets keepers tests
AssetMantle/modules pull request #136
Opened 2022-11-15 09:05 UTC by 0xankit

Add assets keepers tests

## Description

Closes: #XXXX

---

### Author Checklist

*All items are required. Please add a note to the item if the item is not applicable and please add links to any
relevant follow-up issues.*

I have...

- [ ] included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json)
  in the PR title
- [ ] added `!` to the type prefix if API or client breaking change
- [ ] targeted the correct branch (
  see [PR Targeting](https://github.com/AssetMantle/modules/blob/master/CONTRIBUTING.md#pr-targeting))
- [ ] provided a link to the relevant issue or specification
- [ ] followed the guidelines
  for [building modules](https://github.com/AssetMantle/modules/blob/master/docs/building-modules)
- [ ] included the necessary unit and
  integration [tests](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#testing)
- [ ] added a changelog entry to `CHANGELOG.md`
- [ ] included comments for [documenting Go code](https://blog.golang.org/godoc)
- [ ] updated the relevant documentation or specification
- [ ] reviewed "Files changed" and left comments if necessary
- [ ] confirmed all CI checks have passed

### Reviewers Checklist

*All items are required. Please add a note if the item is not applicable and please add your handle next to the items
reviewed if you only reviewed selected items.*

I have...

- [ ] confirmed the
  correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] confirmed `!` in the type prefix if API or client breaking change
- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed state machine logic
- [ ] reviewed API design and naming
- [ ] reviewed documentation is accurate
- [ ] reviewed tests and test coverage
- [ ] manually tested (if applicable)

2022-11-19 11:17 UTC, deepanshutr requested changes
Requesting changes.

2022-11-19 11:17 UTC, deepanshutr commented on modules/assets/internal/transactions/burn/request_test.go
> +	//cliCommand := baseHelpers.NewCLICommand("", "", "", []helpers.CLIFlag{constants.AssetID, constants.FromID})
commented code

2022-11-19 11:17 UTC, deepanshutr commented on modules/assets/internal/transactions/define/request_test.go
> +		// TODO: Add test cases.
?

2022-11-19 11:17 UTC, deepanshutr commented on modules/assets/internal/transactions/mint/request_test.go
> +		// TODO: Add test cases.
?

2022-11-19 11:17 UTC, deepanshutr commented on modules/assets/internal/transactions/mutate/keeper_test.go
> +	//immutableProperties := baseLists.NewPropertyList(baseProperties.NewMesaProperty(baseIDs.NewStringID("ID1"), baseData.NewStringData("ImmutableData")))
!

2022-11-19 11:17 UTC, deepanshutr commented on modules/assets/internal/transactions/mutate/request_test.go
> +		// TODO: Add test cases.
!

2022-11-19 11:17 UTC, deepanshutr commented on modules/assets/internal/transactions/renumerate/request_test.go
> +		//{"+ve",fields{testBaseRequest,fromID.String(),testAssetID.String()},args{},newTransactionRequest(testBaseRequest,fromID.String(),testAssetID.String()),false},
!

2022-11-19 11:17 UTC, deepanshutr commented on modules/assets/internal/transactions/revoke/request_test.go
> +		//{"+ve", fields{testBaseRequest, fromID.String(), fromID.String(), classificationID.String()},args{},newTransactionRequest(testBaseRequest,fromID.String(),fromID.String(),classificationID.String()
!

2022-11-19 11:17 UTC, deepanshutr commented on modules/metas/auxiliaries/supplement/keeper_mock.go
> +		//if property.GetID().Compare(constants.BurnHeightProperty.GetID()) == 0 && property.GetDataID().GetHashID().Compare(baseIDs.GenerateHashID()) == 0 {
!

2022-11-19 11:17 UTC, deepanshutr commented on modules/metas/auxiliaries/supplement/keeper_mock.go
> +	//propertyList = propertyList.Add(baseProperties.NewMetaProperty(constants.BurnHeightProperty.GetKey(), baseData.NewHeightData(baseTypes.NewHeight(1))))
!

2022-11-21 14:49 UTC, 0xankit commented on modules/assets/internal/transactions/burn/request_test.go
> +	//cliCommand := baseHelpers.NewCLICommand("", "", "", []helpers.CLIFlag{constants.AssetID, constants.FromID})
It will be resolved later

2022-11-21 14:53 UTC, 0xankit commented on modules/assets/internal/transactions/mint/request_test.go
> +		// TODO: Add test cases.
FromCLI will be resolved later

2022-11-21 15:03 UTC, 0xankit commented on modules/assets/internal/transactions/mutate/request_test.go
> +		// TODO: Add test cases.
FromCLI will be done later

2022-11-21 15:03 UTC, 0xankit commented on modules/assets/internal/transactions/renumerate/request_test.go
> +		//{"+ve",fields{testBaseRequest,fromID.String(),testAssetID.String()},args{},newTransactionRequest(testBaseRequest,fromID.String(),testAssetID.String()),false},
FromCLI will be done later

2022-11-25 04:54 UTC, deepanshutr submitted a review, later dismissed
Reviewed.

2022-11-25 04:55 UTC, deepanshutr approved these changes
Reviewed.

2022-11-25 04:55 UTC, merged